name: build-pr

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: [Debug, Release]
        frameworks: [net8.0]
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}

  test-tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/git/checkout-bump-tag@main
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
        message: 'build (ci): update to version'
        name: 'GitHub CI on behalf of ${{ github.actor }}'
        bump_patch: true
        dry-run: true

  pack-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1


  test-update-dependencies:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
      with:
        ssh-key: "${{ secrets.DEPLOY_KEY }}"
    - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
    - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
    - id: update-dependencies
      uses: ./.github/jobactions/update-dependencies
    - id: push-updates
      shell: pwsh
      run: git push --dry-run -u origin ${{ steps.update-dependencies.outputs.branch }}
