name: build-branch

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: ${{ fromJson(vars.CONFIGURATIONS) }}
        frameworks: ${{ fromJson(vars.FRAMEWORKS) }}
        include: ${{ fromJson(vars.BUILD_MATRIX) }}
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}
