name: build-pr

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/dotnet-build.yml@main
    with:
      configurations: ${{ vars.CONFIGURATIONS }}
      frameworks: ${{ vars.FRAMEWORKS }}
      include: ${{ vars.BUILD_MATRIX }}
    secrets: inherit

  test-tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/git/checkout-bump-tag@main
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
        message: 'build (ci): update to version'
        name: 'GitHub CI on behalf of ${{ github.actor }}'
        bump_patch: true
        dry-run: true

  pack-nuget:
    needs:
    - build
    uses: kagekirin/gha-py-toolbox/.github/workflows/dotnet-pack-nuget.yml@main
    with:
      configurations: ${{ vars.DEPLOY_CONFIGURATIONS }}
      frameworks: ${{ vars.DEPLOY_FRAMEWORKS }}
      projects: ${{ vars.DEPLOY_PROJECTS }}
    secrets: inherit

  test-update-dependencies:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
      with:
        ssh-key: "${{ secrets.DEPLOY_KEY }}"
    - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
    - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
    - id: update-dependencies
      uses: ./.github/jobactions/update-dependencies
    - id: push-updates
      shell: pwsh
      run: git push --dry-run -u origin ${{ steps.update-dependencies.outputs.branch }}
