name: build-ci

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: [Debug, Release]
        frameworks: [net8.0]
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}

  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
      with:
        ssh-key: "${{ secrets.DEPLOY_KEY }}"
    - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
    - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
    - id: create-tag
      uses: ./.github/jobactions/tag
    - uses: kagekirin/gha-utils/.github/actions/git-push-tag@main
      with:
        remote: origin
        branch: main
        dry-run: false

  test-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        source: [nuget, github]
        include:
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: KageKirin
            token: NUGET_ORG_TOKEN
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GITHUB_TOKEN
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/actions/dotnet/add-registry@main
      with:
        name: ${{ matrix.source }}
        registry: ${{ matrix.registry }}
        username: ${{ matrix.username }}
        token: ${{ secrets[matrix.token] }}
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
