name: build-branch

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: [Debug, Release]
        frameworks: [net8.0]
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}
