name: build-ci

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    uses: kagekirin/gha-py-toolbox/.github/workflows/dotnet-build.yml@main
    with:
      configurations: ${{ vars.CONFIGURATIONS }}
      frameworks: ${{ vars.FRAMEWORKS }}
      include: ${{ vars.BUILD_MATRIX }}
    secrets: inherit


  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/git/checkout-bump-tag@main
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
        name: 'GitHub CI on behalf of ${{ github.actor }}'
        message: 'build (ci): update to version'
        bump_patch: true
        dry-run: false


  pack-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        configurations: ${{ join(fromJson(vars.DEPLOY_CONFIGURATIONS), ' ') }}
        frameworks: ${{ join(fromJson(vars.DEPLOY_FRAMEWORKS), ' ') }}
