name: build-ci

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: ${{ fromJson(vars.CONFIGURATIONS) }}
        frameworks: [net9.0]
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}

  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/git/checkout-bump-tag@main
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
        name: 'GitHub CI on behalf of ${{ github.actor }}'
        message: 'build (ci): update to version'
        bump_patch: true
        dry-run: false

  pack-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    needs: build
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        configurations: Release
        frameworks: |-
          net9.0
          netstandard2.1
