name: Print info about published package

on:
  registry_package:
    types: [published]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Show infos about GitHub
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github) }}

    - name: Show infos about event
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github.event) }}

    - name: Show infos about registry package
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github.event.registry_package) }}
