name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write # allow GITHUB_TOKEN to publish packages
    strategy:
      matrix:
        source: [nuget, github]
        include:
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: KageKirin
            token: NUGET_ORG_TOKEN
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GITHUB_TOKEN
    steps:
    - id: build-pack-publish
      uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack-publish@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
        registry: ${{ matrix.registry }}
        token: ${{ secrets[matrix.token] }}
