name: publish (nuget)

on:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write # allow GITHUB_TOKEN to publish packages
    strategy:
      matrix:
        source: ${{ fromJson(vars.DEPLOY_SOURCES) }}
        include: ${{ fromJson(vars.DEPLOY_MATRIX) }}
    steps:
    - id: build-pack-publish
      uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack-publish@main
      with:
        configurations: ${{ join(fromJson(vars.DEPLOY_CONFIGURATIONS), ' ') }}
        frameworks: ${{ join(fromJson(vars.DEPLOY_FRAMEWORKS), ' ') }}
        registry: ${{ matrix.registry }}
        nuget-token: ${{ secrets[matrix.token] }}
