name: publish-info

on:
  registry_package:
    types: [published]

jobs:
  info:
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: kagekirin/gha-py-toolbox/actions/pip/install@main
      with:
        packages: >-
          PyGithub
          requests

    - name: Show infos about published package
      shell: python
      env:
        json: ${{ toJSON(github) }}
      run: |-
        """
        ${{ toJSON(github) }}
        """

    - id: download-packages
      name: Download published package
      uses: kagekirin/gha-py-toolbox/actions/gh/download-published-nuget-package@main
      with:
        registry_package_json: ${{ toJSON(github.event.registry_package) }}
        token: ${{ github.token }}

    - id: upload-assets
      uses: kagekirin/gha-py-toolbox/actions/gh/upload-release-assets@main
      with:
        token: ${{ github.token }}
        tag: v${{ github.event.registry_package.package_version.version }}
        files: ${{ steps.download-packages.outputs.packages }}
