name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configuration: [Debug, Release]
        framework: [net8.0]
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: kagekirin/gha-dotnet/.github/actions/nuget-add-registry@main
      with:
        name: github-nuget
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/jobactions/build
      with:
        configuration: ${{ matrix.configuration }}
        framework: ${{ matrix.framework }}

  nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write # allow GITHUB_TOKEN to publish packages
    strategy:
      matrix:
        source: [nuget, github]
        include:
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: KageKirin
            token: NUGET_ORG_TOKEN
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GITHUB_TOKEN
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: ./.github/jobactions/nuget-prepare-publish
      with:
        name: ${{ matrix.source }}
        registry: ${{ matrix.registry }}
        username: ${{ matrix.username }}
        token: ${{ secrets[matrix.token] }}
    - uses: kagekirin/gha-dotnet/.github/actions/nuget-publish@main
      with:
        registry: ${{ matrix.registry }}
        token: ${{ secrets[matrix.token] }}
