name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        configurations: [Debug, Release]
        frameworks: [net8.0]
    steps:
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build@main
      with:
        configurations: ${{ matrix.configurations }}
        frameworks: ${{ matrix.frameworks }}

  nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write # allow GITHUB_TOKEN to publish packages
    strategy:
      matrix:
        source: [nuget, github]
        include:
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: KageKirin
            token: NUGET_ORG_TOKEN
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GITHUB_TOKEN
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
    - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
    - uses: kagekirin/gha-dotnet/.github/actions/build@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
    - id: nuget-pack
      uses: kagekirin/gha-dotnet/.github/actions/nuget-pack@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
    - uses: kagekirin/gha-dotnet/.github/actions/nuget-add-registry@main
      with:
        name: ${{ matrix.source }}
        registry: ${{ matrix.registry }}
        username: ${{ matrix.username }}
        token: ${{ secrets[matrix.token] }}
    - uses: kagekirin/gha-dotnet/.github/actions/nuget-publish@main
      with:
        registry: ${{ matrix.registry }}
        token: ${{ secrets[matrix.token] }}
        packages: ${{ steps.nuget-pack.outputs.packages }}
