name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow GITHUB_TOKEN to create releases
    steps:
    - id: create-release
      uses: kagekirin/gha-py-toolbox/actions/gh/create-release@main
      with:
        token: ${{ secrets.GH_RELEASE_TOKEN }}
        title: Release ${{ github.ref_name }}
        generate-notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
