name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow GITHUB_TOKEN to create releases
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
    - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
    - uses: kagekirin/gha-dotnet/.github/actions/build@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
    - id: nuget-pack
      uses: kagekirin/gha-dotnet/.github/actions/nuget-pack@main
      with:
        configurations: Release
        frameworks: |-
          net8.0
          netstandard2.1
    - uses: kagekirin/gha-utils/.github/actions/gh-create-release@main
      with:
        title: Release ${{ github.action_ref }}
        generate-notes: true
        files: |
          ${{ steps.nuget-pack.outputs.packages }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
